spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
